---
title: "R Notebook"
output: html_notebook
---


```{r}
###
###Permutation t tests
###

perm_t_test=function(x,y,iter=1e3){
  
  T0=abs(mean(x)-mean(y))  # define the test statistic
  T_stat=numeric(iter) # a vector to store the values of each iteration
  x_pooled=c(x,y) # pooled sample
  n=length(x_pooled)
  n1=length(x)
  
  for(perm in 1:iter){ # loop for conditional MC
    # permutation:
    permutation <- sample(1:n)
    x_perm <- x_pooled[permutation]
    x1_perm <- x_perm[1:n1]
    x2_perm <- x_perm[(n1+1):n]
    # test statistic:
    T_stat[perm] <- abs(mean(x1_perm) - mean(x2_perm))
    
  }
  
  # p-value
  p_val <- sum(T_stat>=T0)/iter
  return(p_val)
}
```

```{r}
x1 <- data$P_Puntaje_[which(data$CALENDARIO == 1)]
x2 <- data$P_Puntaje_[which(data$CALENDARIO == 3)]

perm_t_test(x1, x2)
```

```{r}
hist(x1)
hist(x2)
```

Schools from Calendario B have different distribution than those from Calendario A.


```{r}
alpha <- 0.05
wilcox.test(x1, y = x2, paired=F, conf.level = 1-alpha,
            alternative = "less")$p.value
```

```{r}
median(x1)
median(x2)
```

With this test we confirm that the median score of students from Calendario B schools is higher than Calendario A.


```{r}
table(data$COD_LOCA)
```

```{r}
###
### ANOVA
###

scores <- data$P_Puntaje_
LOC <- as.factor(data$COD_LOCA)

fit <- aov(scores ~ LOC)
summary(fit)

T0 <- summary(fit)[[1]][1,4]  # extract the test statistic
T0
```


```{R}
B = 1e3

T_stat <- numeric(B) 
n <- dim(data)[1]

for(perm in 1:B){
  # Permutation:
  permutation <- sample(1:n)
  scores_perm <- scores[permutation]
  fit_perm <- aov(scores_perm ~ LOC)
  
  # Test statistic:
  T_stat[perm] <- summary(fit_perm)[[1]][1,4]
}
```

```{r}
hist(T_stat,xlim=range(c(T_stat,T0)),breaks=30)
abline(v=T0,col=3,lwd=2)
```

```{r}
p_val <- sum(T_stat>=T0)/B
p_val
```

```{r}
plot(LOC, scores, xlab='treat',col=rainbow(g),main='Original Data')
```


